Feat/termapi 153 terminal reconnect attempts
fivestars/terminal-api-flows pull request #3
Opened 2022-10-06 15:44 UTC by bogdan-skorobogatov-sumup

2022-10-06 17:39 UTC, chad-lung-fivestars commented on terminal_api_flows/tools/decorators.py
> +            LOGGER.error("Terminal does not respond")
Can you change this to:
"Customer terminal did not respond"

2022-10-07 23:12 UTC, chad-lung-fivestars commented on terminal_api_flows/__init__.py
> +TERMINAL_ID = 2222222  # <-- TERMINAL ID HERE
This can actually have alpha numeric characters so it should stay as a string.
```
TERMINAL_ID = " --> TERMINAL ID HERE <--- "
```

2022-10-07 23:25 UTC, chad-lung-fivestars requested changes
This looks good overall and a nice clean-up - thanks. I just have the one comment and change and I think this is good to go then. I will review it again after that change.

2022-10-10 14:57 UTC, bogdan-skorobogatov-sumup commented
@chad-lung-fivestars done :)

2022-10-10 15:00 UTC, chad-lung-fivestars approved these changes
👍 Please merge, thanks!

2022-10-10 15:01 UTC, merged